name: crd_swagger_transform
description: Transform the output of `kubectl get crd --output=json` to a swagger json
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^1.0.0
